name: Platformio Build Trip5 Firmwares

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Extract first environment
        id: extract_env
        run: |
          # Extract the first environment name from platformio.ini
          first_env=$(grep -oP '(?<=\[env:)[^\]]+' platformio.ini | head -n 1)
          echo "First environment: $first_env"
          echo "env_name=$first_env" >> $GITHUB_ENV

      - name: Build SPIFFS for first environment
        run: pio run --environment ${{ env.env_name }} --target buildfs

      - name: Use SPIFFS from first environment
        run: |
          # Copy the SPIFFS binary for the first environment
          cp .pio/build/${{ env.env_name }}/spiffs.bin .pio/build/spiffs.bin

      - name: Build all environments
        run: pio run

      - name: Rename firmware files with env name
        run: |
          for d in .pio/build/*/ ; do
            env=$(basename "$d")
            if [ -f "$d/firmware.bin" ]; then
              cp "$d/firmware.bin" ".pio/build/${env}.bin"
            fi
          done

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/*.bin

      - name: Extract version
        run: grep '#define YOVERSION ' yoRadio/src/core/options.h > version.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## For these pre-built configurations
            - Board: ESP32-S3-N16R8
              - firmware_esp32_s3_n16r8_test (bare board, no peripherals)
              - [firmware_sh1106_pcm_remote](https://trip5.github.io/yoradio-docs/docs/myoptions-generator.html?b=ESP32-S3-DevKitC-1_44Pin&r=72,2,3,4,6,7,15,43,49,51,52,53,54,75,66&i=5,6,15,16,17,22,23,24,25,26,27,28,29,30,39,45,46,47,40&v=42,41,12,11,10,7,18,15,17,16,255,40,39,38,47,21,13,14,8)
              - [firmware_sh1106_pcm_1button](https://trip5.github.io/yoradio-docs/docs/myoptions-generator.html?b=ESP32-S3-DevKitC-1_44Pin&r=72,2,3,4,6,15,43,49,51,52,53,54,75&i=5,6,15,16,17,22,23,24,25,26,27,28,29,30,39,45,46,47&v=42,41,12,11,10,255,255,255,255,17,255,7,15,16,47,21,13,14)
              - [firmware_ssd1306x32_pcm_1button](https://trip5.github.io/yoradio-docs/docs/myoptions-generator.html?b=ESP32-S3-DevKitC-1_44Pin&r=72,2,3,4,6,17,43,49,51,52,53,54,75&i=5,6,15,16,17,22,23,24,25,26,27,28,29,30,39,45,46,47&v=42,41,12,11,10,255,255,255,255,17,255,7,15,16,47,21,13,14)
              - [firmware_sh1106_vs1053_3buttons](https://trip5.github.io/yoradio-docs/docs/myoptions-generator.html?b=ESP32-S3-DevKitC-1_44Pin&r=72,2,3,4,6,15,44,48,49,51,52,53,54,75&i=5,6,18,19,20,21,22,23,24,25,26,27,28,29,30,39,45,46,47&v=42,41,9,14,10,-1,255,255,255,17,18,16,40,39,38,47,21,2,1)
              - [firmware_st7735_pcm_1button](https://trip5.github.io/yoradio-docs/docs/myoptions-generator.html?b=ESP32-S3-DevKitC-1_44Pin&r=72,2,3,4,6,11,36,43,49,51,52,53,54,75&i=1,2,3,4,15,16,17,22,23,24,25,26,27,28,29,30,39,45,46,47&v=10,9,-1,4,15,7,6,255,255,255,255,42,255,40,39,38,47,21,13,14)
              - [firmware_ili9488_pcm_1button](https://trip5.github.io/yoradio-docs/docs/myoptions-generator.html?b=ESP32-S3-DevKitC-1_44Pin&r=72,2,3,4,6,31,43,49,51,52,53,54,75&i=1,2,3,4,15,16,17,22,23,24,25,26,27,28,29,30,39,45,46,47&v=10,9,-1,4,15,7,6,255,255,255,255,42,255,40,39,38,47,21,2,1)
          files: |
            .pio/build/*.bin
            yoRadio/data/www/*
            version.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
